name: lisataiji_soft_memory_pe
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.11
  - numpy
  - scipy
  - matplotlib
  - pyyaml
  - pip
  - pip:
      - jax
      - jaxlib
      - emcee
      - corner
      - pycbc
